name: my_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  bloc_concurrency: ^0.2.0
  platform_detector: ^0.2.0
  flutter_adaptive_scaffold: ^0.1.8
  async: ^2.11.0
  cupertino_icons: ^1.0.6
  dots_indicator: ^2.1.1
  photo_view: ^0.15.0
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  fonts:
    - family: RobotoSerif
      fonts:
        - asset: fonts/RobotoSerif-Regular.ttf
  assets:
    - assets/images/
  uses-material-design: true
